"""add image_url to blog post

Revision ID: 50232ac1f8df
Revises: 31ab86ea8833
Create Date: 2025-05-07 12:49:52.929922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50232ac1f8df'
down_revision = '31ab86ea8833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('image_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'image_url')
    # ### end Alembic commands ###
